config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  get     '/admin',   to: 'static_pages#admin'

  resources :users
  resources :leads
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user,  only: :admin
  before_action :admin_user,      only: :admin

  def admin
    render 'admin'
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_agiraffe.html.erb
<section id="a_giraffe" class="services bg-coolGrey">
    <div class="container">
        <div class="row content-row">
            <div class="col-md-4 col-sm-4">
                <%= image_tag("OrangeGiraffe.svg", alt: "Know Your Power Watermark", class: "img-responsive center-block", id: "giraffeSectionLogo") %>
            </div>
            <div class="col-md-8 col-sm-6">
                <p class="nexa-light white_text">
                    The giraffe’s iconic feature is its long neck.  Symbolically, this long neck represents reaching out, stretching, and elevating ourselves.  Dream analysts believe that a giraffe in our dreams is a reminder that we are all powerful beings with remarkable potential to not only rise to a challenge, but do so with grace and integrity.
                </p>
                <p class="nexa-light white_text">The giraffe represents long-reaching, far-seeing vision.  With its head lifted as high as the treetops, the giraffe's vision is focused on the horizon. Giraffe’s literally see a "bigger picture."
                </p>
                <p class="nexa-light white_text">
                The giraffe has a steady temper and quiet demeanor.  It is confident in its power.  It doesn’t need to be aggressive or predatory to survive.
                </p>
            </div>
        </div>
    </div>
</section>

app/views/static_pages/_footer.html.erb
<footer class="footer" style="background-color: #53565A">
    <div class="container text-center">
        <div class="row">
           <%= image_tag("OrangeGiraffe.svg", alt: "Head Up Logo", class: "img-responsive img-centered", id: "footerLogo") %>
        </div>
        <div class="row copyright">
            <div class="col-lg-12">
                <p class="nexa-light center orange">&copy; 2017 Head Up, Inc.</p>
            </div>
        </div>
    </div>
</footer>

app/views/static_pages/_getintouch.html.erb
<section class="cta-form bg-dark" id="get_in_touch">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h4>Get In Touch</h4>
                <hr class="colored">
            </div>
        </div>
    </div>
    <div class="row text-center content-row">
        <div class="col-md-6 col-md-offset-3">
                <p class="nexa-bold center mobile-smaller">Tell us about the power you're trying to access.</p>
                <p class="nexa-bold center mobile-smaller">We'll help you find it.</p>
                <%= render 'leads/newLeadForm' %> 
        </div>
    </div>
    <div class="container wow">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <%= image_tag("KYPOrange.svg", alt: "Know Your Power Watermark", class: "img-responsive center-block", id: "knowYourPowerLogo") %>
            </div>
        </div>
    </div>
    <div class="row text-center content-row">
        <div class="col-md-12 col-sm-6">
            <p class="nexa-bold center mobile-smaller">Or, just sign up for our newsletter by entering your email below!</p>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- MailChimp Signup Form -->
                    <div id="mc_embed_signup">
                        <!-- Replace the form action in the line below with your MailChimp embed action! Visit the documentation for additional instructions! -->
                        <form role="form" action="//headupinc.us14.list-manage.com/subscribe/post?u=707e6a775a39a3e7d1425466f&amp;id=e35bb3ff0a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
                            <div class="input-group input-group-lg">
                                <input type="email" name="EMAIL" class="form-control" id="mce-EMAIL" placeholder="Email address...">
                                <span class="input-group-btn">
                                    <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">Power Up!</button>
                                </span>
                            </div>
                            <div id="mce-responses">
                                <div class="response" id="mce-error-response" style="display:none"></div>
                                <div class="response" id="mce-success-response" style="display:none"></div>
                            </div>
                        </form>
                    </div>
                    <!-- End MailChimp Signup Form -->
                </div>
            </div>
            <div class="row top-space-5-percent">
                <div class="col-lg-8 col-lg-offset-2">
                     <ul class="list-inline">
                        <li><a href="https://www.linkedin.com/in/juddstephanie" target="_blank"><i class="fab fa-linkedin fa-5x"></i></a>
                        </li>
                    </ul> 
                </div>
            </div>
        </div>
    </div>


</section>

app/views/static_pages/_header.html.erb
<header id="page-top" class="video">
    <div class="overlay"></div>
    <div class="intro-content">
        <%= image_tag("OrangeHorizontal.svg", alt: "Head Up Logo", class: "img-responsive img-centered", id: "headerLogo") %>
    </div>
    <div class="scroll-down row">
        <div class="col-md-12" >
            <a class="btn page-scroll vert-center padding-arrow" href="#work_with_me"><i class="fa fa-angle-double-down fa-5x"></i></a>
            <% if logged_in? %>
            <a class="btn float-right padding-signin" href="/logout" data-method="delete"><i class="fa fa-sign-out fa-1x"></i></a>
            <% else %>
            <a class="btn float-right padding-signin" href="/login"><i class="fa fa-sign-in fa-1x"></i></a>
            <% end %>
        </div>
    </div>
</header>

<!-- <header id="page-top" class="mobile-full" style="background-image: url(<%= asset_path 'TableOffice.jpg' %>);">
    <div class="intro-content">
      <%= image_tag("OrangeHorinzontal.svg", alt: "Head Up Logo", class: "img-responsive img-centered shadow", id: "headerLogo") %>
    </div>
    <div class="scroll-down">
        <a class="btn page-scroll" href="#stephanie_who"><i class="fa fa-angle-double-down fa-5x"></i></a>
    </div>
</header> -->

app/views/static_pages/_powerup.html.erb
<section id="power_up">
    <div class="container wow fadeIn">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h4>Get In Touch</h4>
                <hr class="colored">
                <p class="nexa-bold center mobile-smaller">Tell us about the power you're trying to access.  We'll help you find it.</p>
            </div>
        </div>
        <div class="row content-row">
            <div class="col-lg-8 col-sm-offset-2">
                <%= render 'leads/newLeadForm' %> 
            </div>
        </div>
    </div>
</section>

app/views/static_pages/_process.html.erb
<section id="process" class="services bg-gray">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-12 wow fadeIn">
                <h2>Our Process</h2>
                <hr class="colored">
                <p>Here is an overview of how we approach each new project</p>
            </div>
        </div>
        <div class="row content-row">
            <!-- Service Item 1 -->
            <div class="col-md-4 wow fadeIn" data-wow-delay=".2s">
                <div class="media">
                    <div class="pull-left">
                        <i class="fa fa-clipboard"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Plan</h3>
                        <ul>
                            <li>Client interview</li>
                            <li>Gather consumer data</li>
                            <li>Create strategy</li>
                            <li>Analyze research</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Service Item 2 -->
            <div class="col-md-4 wow fadeIn" data-wow-delay=".4s">
                <div class="media">
                    <div class="pull-left">
                        <i class="fa fa-pencil"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Create</h3>
                        <ul>
                            <li>Gather team feedback</li>
                            <li>Build business plan</li>
                            <li>Map workflow</li>
                            <li>Build iterative feedback mechanism</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Service Item 3 -->
            <div class="col-md-4 wow fadeIn" data-wow-delay=".6s">
                <div class="media">
                    <div class="pull-left">
                        <i class="fa fa-rocket"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Execute</h3>
                        <ul>
                            <li>Market product launch</li>
                            <li>Collect UX data</li>
                            <li>Deploy product</li>
                            <li>Quarterly review</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/static_pages/_quote1.html.erb
<aside class="cta-quote" style="background-image: url(<%= asset_path 'Leap.jpg' %>);">
    <div class="container wow fadeIn">
        <div class="row">
            <div class="col-md-10 col-md-offset-1" data-wow-delay=".1s">
                <span class="quote" id="quote_1">“Whatever you can do <br/> or dream you can, <br/>begin it.  <br/>Boldness has genius, <br/>power, <br/>and magic in it.”</span>
                <hr class=" colored">
                <span class="quote" id="quote_1_author">Goethe</span>
            </div>
        </div>
    </div>
</aside>

app/views/static_pages/_quote2.html.erb
<aside class="cta-quote" style="background-image: url(<%= asset_path 'RedRocksClimbing.jpg' %>);">
    <div class="container wow fadeIn">
        <div class="row">
            <div class="col-md-6 col-md-offset-1 col-sm-6 float-right" data-wow-delay=".1s">
                <span class="quote" id="quote_2">“Why fit in, when you were born to stand out?”</span>
                <hr class=" colored">
                <span class="quote" id="quote_2_author">Dr. Seuss</span>
            </div>
        </div>
    </div>
</aside>

app/views/static_pages/_stephaniewhoOLD.html.erb
<!-- Portfolio Carousel -->
<section class="portfolio-carousel" id="stephanie_who">
    <!-- NOTE: You can add more items to the carousel, or remove items you don't need! -->
    <!-- Carousel Item 1 -->    
    <div class="item">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h4>I’m Stephanie!</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-sm-push-6">
                    <%= image_tag("stephanieHeadshot2.jpg", alt: "Stephanie", class: "img-responsive center-block", id: "stephanieMain") %>
                </div>
                <div class="col-md-5 col-md-offset-1 col-sm-pull-6">
                    <p class="nexa-light intro-text-spacing">I like to think of myself as a life-long seeker of adventure, all geared toward the end-game of fully knowing what I’m capable of.</p>
                    <p class="nexa-light intro-text-spacing text">AND…</p>
                    <p class="nexa-light intro-text-spacing">I’m here to help you expand and unleash what you’re capable of too!</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Carousel Item 2 -->
    <div class="item">
        <div class="container text-center wow fadeIn">
            <div class="row">
                <div class="col-md-12 col-sm-6">
                    <h4 class="h4-mobile">Want to know my credentials?</h4>
                    <h4 class="h4-mobile mobile-hide">Here they are.  But really, they’re just formalities.</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <br>  
                    <ul class="no-bullet-mobile">
                        <li><p class="nexa-light bullet-spacing bullet-mobile">Trained as a Coach by the Coaches Training Institute</p></li>
                        <hr class="colored desktop-hide">
                        <li><p class="nexa-light bullet-spacing bullet-mobile">5 years of experience consulting in the Executive Leadership Development and Organizational Culture spaces</p></li>
                        <hr class="colored desktop-hide">
                        <li><p class="nexa-light bullet-spacing bullet-mobile">M.B.A., with a focus on Transformational Leadership and Organizational Behavior, Ross School of Business, University of Michigan</p></li>
                        <hr class="colored desktop-hide">
                        <li><p class="nexa-light bullet-mobile">M.S., with a focus on Policy and Behavior Change, School of Natural Resources & the Environment, University of Michigan</p></li>
                    </ul>      
                </div>
            </div>
        </div>
        <div class="container text-center wow fadeIn">
            <div class="col-lg-12">
                <p class="nexa-bold bullet-mobile">The best thing you can do is reach out!  There’s nothing I’d love more than getting to know you and your power.</p>
                 <ul class="list-inline">
                    <li><a href="https://www.facebook.com/wugzoogle" target="_blank"><i class="fa fa-facebook fa-fw fa-2x orange"></i></a>
                    </li>
                    <li><a href="https://twitter.com/HeadUpInc" target="_blank"><i class="fa fa-twitter fa-fw fa-2x orange"></i></a>
                    </li>
                    <li><a href="https://www.linkedin.com/in/juddstephanie" target="_blank"><i class="fab fa-linkedin fa-2x"></i></a>
                    </li>
                </ul> 
            </div>
        </div>
    </div>

    <!-- Carousel Item 3 -->

</section>

app/views/static_pages/_testimonials.html.erb
<section class="testimonials bg-gray" id="testimonials">
    <div class="container wow fadeIn">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <div class="testimonials-carousel">
                    <!-- NOTE: You can add more items to the carousel, or remove items you don't need! -->
                    <!-- Testimonial Item 1 -->
                    <div class="item">
                        <div class="row">
                            <div class="col-lg-12">
                                <p class="lead">"Working with Head Up was both a valuable and rewarding experience."</p>
                                <hr class="colored">
                                <p class="quote">These guys are really good. I mean like really really good. I can't tell you how good they are because there just are no words. I can't.</p>
                                <div class="testimonial-info">
                                    <div class="testimonial-img">
                                        <%= image_tag("alex.jpg", alt: "Testi1", class: "img-circle img-responsive") %>
                                    </div>
                                    <div class="testimonial-author">
                                        <span class="name">Alex Papo</span>
                                        <p class="small">McKinsey</p>
                                        <div class="stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial Item 2 -->
                    <div class="item">
                        <div class="row">
                            <div class="col-lg-12">
                                <p class="lead">"Head Up increased our revenues by over 2000%! I can't recommend them enough."</p>
                                <hr class="colored">
                                <p class="quote">Seriously, did you see what Alex said? Like that, but just 2000% better. Since I've started working with Head Up, I have experienced a level of personal growth I couldn't have imagined before.</p>
                                <div class="testimonial-info">
                                    <div class="testimonial-img">
                                        <%= image_tag("ursula.jpg", alt: "Testi2", class: "img-circle img-responsive") %>
                                        <!-- <img src="assets/images/agency/testimonials/2.jpg" class="img-circle img-responsive" alt=""> -->
                                    </div>
                                    <div class="testimonial-author">
                                        <span class="name">Ursula Jessee</span>
                                        <p class="small">Hach</p>
                                        <div class="stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial Item 2 -->
                    <div class="item">
                        <div class="row">
                            <div class="col-lg-12">
                                <p class="lead">"I'm never going to work with any another consulting company again. These guys are the cat's pyjamas"</p>
                                <hr class="colored">
                                <p class="quote">After suffering through a parade of incompetent assholes, Head Up was like a breath of fresh air blowing away the stank!</p>
                                <div class="testimonial-info">
                                    <div class="testimonial-img">
                                        <%= image_tag("stephen.jpg", alt: "Testi2", class: "img-circle img-responsive") %>
                                        <!-- <img src="assets/images/agency/testimonials/2.jpg" class="img-circle img-responsive" alt=""> -->
                                    </div>
                                    <div class="testimonial-author">
                                        <span class="name">Stephen</span>
                                        <p class="small">Self-made millionare</p>
                                        <div class="stars">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/static_pages/_workwithme.html.erb
<section id="work_with_me">
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-lg-12 wow fadeIn">
                <h4>Work With Us</h4>
                <hr class="colored">
                <div class="col-lg-6 col-lg-offset-3">
                <h5>“If you want to build a ship, don’t drum up the people to gather wood, divide the world, and give orders.  Instead, teach them to yearn for the vast and endless sea.”</h5>
                <h5>- Antoine de Saint-Exupery</h5>
                </div>
            </div>
        </div>
        <div class="row text-center content-row">
            <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                <div class="about-content">
                    <i class="fas fa-bullhorn fa-4x"></i>
                    <p class="majesti-book bigger">Coaching</p>
                    <p class="nexa-light smaller">As a trained coach by Coaches Training Institute, Stephanie will work one-on-one with you or any of your team members to unlock the power you need to grow your business and build the life you want.</p>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay=".4s">
                <div class="about-content">
                    <i class="far fa-comments fa-4x"></i>
                    <p class="majesti-book bigger">Speaking</p>
                    <p class="nexa-light smaller">Stephanie speaks on topics that around inspiration, leadership, habits, authenticity, and basically all things related to knowing your power.  If you’d like to book a talk, reach out.</p>
                </div>
            </div> 
        </div>
        <div class="text-center col-lg-6 col-lg-offset-3 wow fadeIn">
            <h5>Stephanie works with her business partner, Kara, to create experiences that change how people think and act:</h5>
        </div>
       
        <div class="row text-center content-row">
            <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                <div class="about-content">
                    <%= image_tag("wolfAndHeron.png", alt: "Wolf & Heron", class: "img-responsive center-block", id: "wolfAndHeronLogo") %>
                    <p class="majesti-book bigger">Wolf & Heron</p>
                    <p class="nexa-light smaller">At <%= link_to "Wolf & Heron", "http://www.wolfandheron.com/", target: "_blank" %>, we design experiences and workshops that are highly immersive, offering the next wave of leaders the opportunity to discover, share insights, and build capabilities in a fun, interactive way.</p>
                </div>
            </div> 
            <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay=".4s">
                <div class="about-content">
                    <%= image_tag("cairnConcept.png", alt: "Carin Concept", class: "img-responsive center-block", id: "carinConceptLogo") %>
                    <p class="majesti-book bigger">The Cairn Concept</p>
                    <p class="nexa-light smaller">At <%= link_to "The Cairn Concept", "http://www.thecairnconcept.com/", target: "_blank" %>, we provide organizations with the strategies and tools they need to change the way their people think and act through a high-touch, customized, consultative approach.</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/static_pages/admin.html.erb
<section id="admin" class="services bg-coolGrey">
    <div class="container">
    <h1>Admin Panel</h1>
    <% if !flash.empty? %>
      <%= render 'shared/flash_no_section' %>
    <% end %>
        <%= link_to "Users", users_path, class: "btn btn-primary btn-lg btn-block" %>
        <%= link_to "Leads", leads_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
</section>

app/views/static_pages/home.html.erb
<!-- Header -->
<%= render 'header' %>

<!-- Flash Section -->
<% if !flash.empty? %>
    <%= render 'shared/flash' %>
<% end %>

<!-- Work With Me Section -->
<%= render 'workwithme' %>

<!-- A Giraffe Section -->
<%= render 'agiraffe' %>

<!-- Goethe Quote -->
<%= render 'quote1' %>

<!-- Get In Touch Section -->
<%= render 'getintouch' %>

<!-- Newsletter Signup Section -->
<!-- <%= render 'powerup' %> -->

<!-- Dr. Seuss Quote -->
<%= render 'quote2' %>

<!-- Stephanie Who? Section -->
<%= render 'stephaniewho' %>


<!-- Process Section -->
<!-- Pending until we figure out if we want to use this section. Might need to rename. -->

<!-- Portfolio Carousel Section-->
<!-- Pending until we get portfolio information. -->

<!-- Testomonials Section -->
<!-- Pending until we get testimonials. -->


<!-- Blog Section -->
<!-- Pending until I implement blog feature. -->

<!-- Footer -->
<%= render 'footer' %>